# Generated by Django 5.2 on 2025-04-08 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('requires_obligations', models.BooleanField()),
                ('required_licenses', models.CharField(max_length=300)),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReputationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('reputation_grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=50)),
                ('min_altitude', models.IntegerField()),
                ('max_altitude', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('restrictions', models.CharField(max_length=100)),
                ('obligations', models.CharField(max_length=100)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.license')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='required_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.reputationlevel'),
        ),
        migrations.CreateModel(
            name='TheoreticalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option_a', models.CharField(max_length=150)),
                ('option_b', models.CharField(max_length=150)),
                ('option_c', models.CharField(max_length=150)),
                ('option_d', models.CharField(max_length=150)),
                ('correct_answer', models.CharField(max_length=1)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.license')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('first_access', models.BooleanField()),
                ('email_verified', models.BooleanField()),
                ('login_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_failed_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('last_failed_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_failed_latitude', models.FloatField(blank=True, null=True)),
                ('last_failed_longitude', models.FloatField(blank=True, null=True)),
                ('preferred_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.currency')),
                ('reputation_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.reputationlevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('first_issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.license')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_id', models.CharField(max_length=13)),
                ('score_date', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('reputation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.reputationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.userprofile')),
            ],
        ),
    ]
