# Generated by Django 5.2 on 2025-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.DeleteModel(
            name='UserEconomy',
        ),
    ]
